config/routes.rb
Rails.application.routes.draw do
  
root 'homepage#index'
 resources :order_items
 devise_for :users, controllers: {
   sessions: 'users/sessions'
  }
  get 'cart', to: 'cart#show'
  resources :products
  resources :admin
  resources :homepage
  resources :order_items
  resources :orders
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_items
   
    belongs_to :user
    
    before_save :set_subtotal

    def subtotal
        order_items.collect { |order_item| order_item.valid? ? order_item.unit_price * order_item.quantity : 0 }.sum
    end

    private
    
    def set_subtotal
        self[:subtotal] = subtotal
    end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    belongs_to :product
    belongs_to :order

    before_save :set_unit_price
    before_save :set_total


def unit_price
    # If there is a record
    if persisted?
      self[:unit_price]
    else
      product.price
    end
end

def total
  unit_price * quantity
end

private
  
 def set_unit_price
   self[:unit_price] = unit_price
 end

  def set_total
   self[:total] = total * quantity
  end  
end 

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :user
    has_many :order_items
    has_one_attached :image

    validates :title, presence: true, length: { maximum: 100 }
    validates :price, presence: true, numericality:{only_integer: true}, length: { maximum: 7 }
    validates :description, presence: true, length: { maximum: 10000 }
    validates :image, presence: true
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify :strict => true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }

  has_many :products
  has_many :orders

 after_create :assign_default_role
 validate :must_have_a_role, on: :update



 private

 after_create :assign_default_role

  def assign_default_role 
    self.add_role(:customer) if self.roles.blank?
  end

  def must_have_a_role
    unless roles.any? 
      errors.add(:roles, "must have role")
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  def index
    @users = User.all
  end
  
  def new
   @user=User.new
  end
  
  def create
   @user = User.create(user_params)
   if @user.save
    @user.remove_role :customer
    @user.add_role :vendor
    redirect_to admin_index_path
   else
    redirect_to new_admin_path, notice: "Failed to create new vendor"
   end
  end
  
  def edit
   @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_index_path, notice: "Role updated"
    else
      flash.now[:error] = "Error: must assigned role"
      render :edit
    end
   end

    def destroy
      @user = User.find(params[:id])
      @user.destroy
      redirect_to root_path, status: :see_other
    end
  
    private
    def user_params
      params.require(:admin).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @order_items=current_order.order_items
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
    before_action :authenticate_user!
    protect_from_forgery prepend: true
   
    
    def index

      
        if current_user.has_role? :admin
            redirect_to admin_index_path 
        elsif current_user.has_role? :vendor
            redirect_to products_path
        else 
           
     end  


        @products = Product.all

        @order_item = current_order.order_items.new


    end
    
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = current_user.orders
  end
  
  def show
    @order = Order.find(params[:id])
    @orders = current_user.orders
  end

  def new
    @order = Order.new
    @order_items=current_order.order_items
  end

  def create
    @order = Order.new(order_params)
    @order.order_items << current_order.order_items
    @order.user = current_user
    if @order.save
      redirect_to orders_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    
    redirect_to root_path, status: :see_other
  end

  private
    def order_params
      params.require(:order).permit(:email,:address,:postal_code,:user_id)
    end
    
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :set_product, only: %i[ show edit update destroy ]
    
    before_action :authenticate_user!, except: [:show]
    
    def index
        @products = current_user.products
    end
    
    def show
    end
    
    def new
        @product = Product.new
    end
    
    def edit
    end
    
    def create
        @product = Product.new(product_params)
        @product.user = current_user
        respond_to do |format|
        if @product.save
            format.html { redirect_to product_url(@product), notice: "Product  was successfully created." }
            format.json { render :show, status: :created, location: @product_page }
        else
            format.html { render :new, status: :unprocessable_entity }
            format.json { render json: @product.errors, status: :unprocessable_entity }
        end
        end
    end
    
    def update
        respond_to do |format|
        if @product.update(product_params)
            format.html { redirect_to product_url(@product), notice: "Product  was successfully updated." }
            format.json { render :show, status: :ok, location: @product }
        else
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @product.errors, status: :unprocessable_entity }
        end
        end
    end
    
    def destroy
        @product.destroy
    
        respond_to do |format|
        format.html { redirect_to products_url, notice: "Product  was successfully destroyed." }
        format.json { head :no_content }
        end
    end
    
    private
        def set_product
         @product = Product.find(params[:id])
        end
    
        def product_params
        params.require(:product).permit(:title, :price, :description, :image,:user_id)
        end
      
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

# for order creation
    
def current_order
        
        if Order.find_by_id(session[:order_id]).nil?
            order = Order.new(user: current_user)
        else
            Order.find_by_id(session[:order_id])
        end
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/home_pages_helper.rb
module HomePagesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/product_pages_helper.rb
module ProductPagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/cart/_cart_items.html.erb
<% @order_items.each do |item| %>
<h3><%= item.product.name %>: </h3>
<h3><%= item.product.price %> :</h3>

<%= form_with model: item do |f| %>
    <%= f.hidden_field :product_id, value: item.product.id %>
    <%= f.number_field :quantity, value: item.quantity.to_i %>
    <%= f.submit "Update Cart" %>
    <%= link_to "Remove Items", item, method: :delete %>
<% end %>    
<h2>Subtotal:<%= item.total %> </h2>
<% end %>    


<h3> Your Current order has Total of: <%= current_order.subtotal %> </h3>

app/views/cart/show.html.erb
 <div id="cart-item" >
   <h3>you are <%= current_user.email %> </h3>
   <% @order_items.each do |item| %>
     <div> Your Item is : <b><%=item.product.title%></b></div> 
     <div> Price Of your product per one unit is : <b><%=item.product.price%> </b></div>
     <div> Quantity is : <b><%=item.quantity%> </b></div>
     <%= image_tag(item.product.image, style:'width:40%') %>            
         
 <%= form_with model: item do |f| %>
     <%= f.hidden_field :product_id, value: item.product.id %>
     <%= f.number_field :quantity, value: item.quantity.to_i, min:1 %>
     <%= f.submit "Update Cart" %>
     <%= link_to "Remove Items", item, data: {
                    method: :delete,
                    confirm: "Are you sure?"
                  }
     %>      
 <% end %> 

     <h5>Subtotal:<%= item.total %></h5>

<% end %>    
    <h3> Your Current order has Total of: <%= current_order.subtotal %> </h3>
    <%= link_to "Shop More..", homepage_index_path %>
    <%= link_to "Check Out", new_order_path %>

</div> <hr>

app/views/homepage/index.html.erb
<h1>Customer</h1>
<h3>you are <%= current_user.email %> </h3>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Price</th>
      <th>Description</th>
      <th>image</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody> 
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.price %></td>
        <td><%= product.description %></td>
        <td> <%= image_tag(product.image, style:'width:500px')%> </td>
        <td>
          <%= form_with model: @order_item do |f| %>
          <%= f.hidden_field :product_id, value: product.id %>
          <%= f.number_field :quantity, value: 1, min: 1 %>
          <%= f.submit "Add To Cart" %>
        </td>
      </tr>
      <% end %>
  </tbody>
</table>
<% end %>
<br>


<%= link_to "Your Total is $#{current_order.subtotal} clicks to proceed", '/cart' %> 
<%= link_to 'View Orders', orders_path %>

<br>
<% if current_user %>
<%= link_to "Edit Info", edit_user_registration_path %>
<br>
<%= link_to "Sign out", destroy_user_session_path,:method => 'delete', data: {confirm: 'Are you sure?'} %>
<% else %>
<%= link_to "Sign Up",  new_user_registration_path %> <br>
<%= link_to "Sign In",  new_user_session_path %> <br>
<% end %>