config/routes.rb
Rails.application.routes.draw do
  
root 'homepage#index'
 resources :order_items
 devise_for :users, controllers: {
   sessions: 'users/sessions'
  }
  get 'cart', to: 'cart#show'
  resources :products
  resources :admin
  resources :homepage
  resources :order_items
  resources :orders
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_items
   
    belongs_to :user
    
    before_save :set_subtotal

    def subtotal
        order_items.collect { |order_item| order_item.valid? ? order_item.unit_price * order_item.quantity : 0 }.sum
    end

    private
    
    def set_subtotal
        self[:subtotal] = subtotal
    end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    belongs_to :product
    belongs_to :order

    before_save :set_unit_price
    before_save :set_total


def unit_price
    # If there is a record
    if persisted?
      self[:unit_price]
    else
      product.price
    end
end

def total
  unit_price * quantity
end

private
  
 def set_unit_price
   self[:unit_price] = unit_price
 end

  def set_total
   self[:total] = total * quantity
  end  
end 

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :user
    has_many :order_items
    has_one_attached :image

    validates :title, presence: true, length: { maximum: 100 }
    validates :price, presence: true, numericality:{only_integer: true}, length: { maximum: 7 }
    validates :description, presence: true, length: { maximum: 10000 }
    validates :image, presence: true
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify :strict => true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }

  has_many :products
  has_many :orders

 after_create :assign_default_role
 validate :must_have_a_role, on: :update



 private

 after_create :assign_default_role

  def assign_default_role 
    self.add_role(:customer) if self.roles.blank?
  end

  def must_have_a_role
    unless roles.any? 
      errors.add(:roles, "must have role")
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  def index
    @users = User.all
  end
  
  def new
   @user=User.new
  end
  
  def create
   @user = User.create(user_params)
   if @user.save
    @user.remove_role :customer
    @user.add_role :vendor
    redirect_to admin_index_path
   else
    redirect_to new_admin_path, notice: "Failed to create new vendor"
   end
  end
  
  def edit
   @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_index_path, notice: "Role updated"
    else
      flash.now[:error] = "Error: must assigned role"
      render :edit
    end
   end

    def destroy
      @user = User.find(params[:id])
      @user.destroy
      redirect_to root_path, status: :see_other
    end
  
    private
    def user_params
      params.require(:admin).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @order_items=current_order.order_items
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = current_user.orders
  end
  
  def show
    @order = Order.find(params[:id])
    @orders = current_user.orders
  end

  def new
    @order = Order.new
    @order_items=current_order.order_items
  end

  def create
    @order = Order.new(order_params)
    @order.order_items << current_order.order_items
    @order.user = current_user
    if @order.save
      redirect_to orders_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    
    redirect_to root_path, status: :see_other
  end

  private
    def order_params
      params.require(:order).permit(:email,:address,:postal_code,:user_id)
    end
    
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

# for order creation
    
def current_order
        
        if Order.find_by_id(session[:order_id]).nil?
            order = Order.new(user: current_user)
        else
            Order.find_by_id(session[:order_id])
        end
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/home_pages_helper.rb
module HomePagesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/product_pages_helper.rb
module ProductPagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/admin/edit.html.erb
  <h2>Update User Role</h2>
  <h3>you are <%= current_user.email %> </h3>
  <%= form_for(:admin, :url => {:action => 'update', :id => @user.id}, method: :put) do |f| %>
    <%= f.collection_check_boxes :role_ids, Role.where(:name=> "vendor"), :id, :name %>
    <%= submit_tag("Update") %>  
  <% end %>

app/views/admin/index.html.erb
  <h1>Admin Panel</h1>
  <h3>you are <%= current_user.email %> </h3>
  <ul>
    <% @users.each do |user| %>
  <li>
      <%= user.email %>
      <%= user.roles.pluck(:name) %>
      <%= link_to "Edit", edit_admin_path(user) %> 
      <%= link_to "Destroy", admin_path(user), data: {
          method: :delete,
          confirm: "Are you sure?"} %>
  </li>
  <% end %>
  </ul>
  <%= link_to "Add Vendor",  new_admin_path %>
  <%= link_to "Edit Info", edit_user_registration_path %>
  <%= link_to "Sign out", destroy_user_session_path,:method => 'delete', data: {confirm: 'Are you sure?'} %>

app/views/admin/new.html.erb
  <h1>Add New vendor</h1>

  <h3>you are <%= current_user.email %> </h3>
  <%= form_for(:admin, :url => {:action => 'create'}) do |f| %>
    <div>
      <%= f.label :email %><br>
      <%= f.email_field :email %>
    </div>
    <div>
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation%>
    </div>
    <div>
      <%= submit_tag("Create Vendor") %>
    </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EComApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>


    <%= yield %>
  </body>
</html>